# Generated by Django 6.0.1 on 2026-01-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_disliked_by_post_liked_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
