# Generated by Django 6.0.1 on 2026-01-17

from django.db import migrations, models


def forwards_copy_reactions(apps, schema_editor):
    Post = apps.get_model("posts", "Post")
    db_alias = schema_editor.connection.alias

    for post in Post.objects.using(db_alias).all():
        liked_ids = list(post.liked_by.values_list("id", flat=True))
        disliked_ids = list(post.disliked_by.values_list("id", flat=True))

        post.liked_by_json = liked_ids
        post.disliked_by_json = disliked_ids
        post.likes = len(liked_ids)
        post.dislikes = len(disliked_ids)
        post.save(update_fields=["liked_by_json", "disliked_by_json", "likes", "dislikes"])


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_post_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="liked_by_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="post",
            name="disliked_by_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(forwards_copy_reactions, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="post",
            name="liked_by",
        ),
        migrations.RemoveField(
            model_name="post",
            name="disliked_by",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="liked_by_json",
            new_name="liked_by",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="disliked_by_json",
            new_name="disliked_by",
        ),
    ]
